version: '3.8'

services:
  mysql-primary:
    image: mysql:8.0
    container_name: mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: demo
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - ./primary-data:/var/lib/mysql
      - ./init_primary.sql:/docker-entrypoint-initdb.d/init_primary.sql
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=demo --default-authentication-plugin=mysql_native_password

  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: demo
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - ./replica-data:/var/lib/mysql
    depends_on:
      - mysql-primary
    command: --server-id=2 --relay-log=relay-bin --log-bin=mysql-bin --read-only=1 --default-authentication-plugin=mysql_native_password

volumes:
  primary-data:
  replica-data:
